### PR TITLE
Playback

### PR DESCRIPTION
**Pull request by logi85**
Hello,

this is a working player. it works under linux with xdotool installed and chrome.
It uses the build-in kodi-keys to control netflix. So it is also possible to control without keyboard.
This is no solution for windows, but perhaps you can integrate it and add a windows-switch later.
Don't want to create another fork, just want a working netflix addon.

Closed first pull request, added audio-playback-fix & movie-playback-fix.

### CODE REVIEW

**Comment by logi85** [comment]
Ok,

now added multithreading, so the loading is much faster. please check this version.

**Comment by z-e-r-o** [comment]
I included your code into mine. The code base was already different. I tried my best but somewhere an error occured. It is currently not working. Can you help to find it?

**Comment by z-e-r-o** [comment]
Looks like windows doesn't like multiprocessing of kodi.
Tried a lot of things and it is not working.
I think multithreading should work for both, windows and Linux.

**Comment by z-e-r-o** [comment]
Can you try my fork if it is working at your machine?
What kind of OS, kodi and Python version have you running?

**Comment by logi85** [comment]
Yes I'll try but need some time. I Use Kodi 16.0-Beta 2 (Nov 22) and Ubuntu 15.10. I think kodi brings it own python interpreter, however on the maschine python 2.7.10 is installed. 
Will pull your changes and have a look on it.

**Comment by logi85** [comment]
What does exactly mean 'don't like'? I've found a problem with the sessions and will try to fix. Please have a look on log. My changes are based on your version (10.12.). I rebased my changes. Only README added/changed. So I can say yes, your version works, but have also problems with correct profile (saw there is an open issue). It loads the wrong movies sometimes.

**Comment by z-e-r-o** [comment]
I'm running Windows 10 with kodi 15.2.
The part with multiprocessing is not working correctly.
I see that 4 additional processes are starting and in kodi I see the progress window.
It is running and running and running....
I saw a thread in kodi forum back from 2013 that there could be a problem with multiprocessing within Windows.

**Comment by logi85** [comment]
I'll try if i have a stable solution on Windows.  I think you could use my player-solution on windows too, i think it should be able to switch the shell-script to a bash script if windows. And if there is a solution like xdotool on windows, controlling netflix would be possible too. Perhaps something like the first answer:
http://stackoverflow.com/questions/19351758/how-to-open-a-program-in-python-and-send-keystrokes

**Comment by logi85** [comment]
hey, now it looks fine! please check my newest version. uhmm.. there are problems with the right data. for example 'my list' ist showing the wrong section. but i allso fixed the profile-switching. the api throws an exception so it cannot be used anymore :/ so i use the frontend-url instead

**Comment by logi85** [comment]
ok, checked performance. loaded the german kid-series. 155 items. without multiprocessing 5 minutes, with mulitprocessing 2 minutes. the most time is lost waiting for moviedb, cause they only allow 30 requests/10 seconds.

**Comment by logi85** [comment]
It should now be possible to use the player on windows. (with Chrome). But no remote-control yet

**Comment by z-e-r-o** [comment]
Currently on holiday and abroad.
So it will take some time to include the changes.

**Comment by logi85** [comment]
OK no problem thx for information

**Comment by jwhite** [comment]
This looks like it was close without merging or am I missing something?

**Comment by logi85** [comment]
Hi,

closed cause I don't think it makes sense to merge.

2016-01-02 22:54 GMT+01:00 Jeremy White <notifications@github.com>:

**Comment by z-e-r-o** [comment]
Still abroad. Soon I will take a look into it and start merging.
Maybe I will not merge everything because of a different way I see.
Let's get the best out of it. ;)

**Comment by jwhite** [comment]
I think Logi has his own branch/repository published.

 

Not sure what he is doing but I’m sure it will get straightened out.

 

-Jeremy

**Comment by logi85** [comment]
Would be great if there will be two running plugins so they can benefit each other.

**Pull request closed without merging**
